### ISSUE TITLE
Category dropdown is broken

### ISSUE THREAD

**Issue by martin-kostov** [Kodular-Community/Discourse-Theme#12]
Here's how it looks like with the latest commit, before it was fine: 
![image](https://user-images.githubusercontent.com/53234486/95010345-3bb7d680-0631-11eb-857b-f50ea7ba521b.png)

And with light mode:
![image](https://user-images.githubusercontent.com/53234486/95010352-52f6c400-0631-11eb-8732-29de54e369d4.png)

**Comment by fahadboss10** [comment]
Working fine for me:
![image](https://user-images.githubusercontent.com/33480925/95011058-7462aa80-0647-11eb-88c9-4625b04072de.png)

Tested on:
- [x] Microsoft Edge (64 Bit)(Chromium)
- [x] Firefox (64 Bit) Windows 10 64 Bit

**Comment by yanquisalexander** [comment]
@MartinStealth From what I see the site you are showing is not Kodular Community 

Could you tell me the URL of your site?

**Comment by Kanishka-Developer** [comment]
I think this issue can now be closed, following the fix deployed on 1st July 2021.
